### ISSUE TITLE
File permission issue with .XML file

### ISSUE THREAD

**Issue by andbillions** [elman22/pocket-amc-reader#26]
Updated to Android 11, Pocket AMC v2.3.1 recently.

The application now reports an error about bad characters when attempting to reload the library .xml file.
When browsing for a library .xml file, no .xml files are shown in the directory that contain the .xml file.

The application permission says "Allow access to media only". I think the requested permission should be "Allow management of all files".

Downgrading to v2.3.0 fixes this for me. (The permission is then "Allow management of all files", and .xml files appear as expected.)

![mediaonly](https://user-images.githubusercontent.com/20376073/94499771-88cc2080-01cb-11eb-96a2-8a5893d7952b.png)
![badchars](https://user-images.githubusercontent.com/20376073/94499773-8964b700-01cb-11eb-9b27-687703efb9e6.png)

**Comment by elman22** [comment]
Thanks for reporting.

"Allow management of all files" for Android 11 won't work for me since Google allows only certain types of applications to have this permission.

So for now I have reverted the changes and file picker in 2.3.2 will work just like it did in 2.3.0.

Fixed in commit 1a7b547ca954e5e5c2c5bcc4e1901fd6431aa415.
